await page.goto('http://103.230.216.39:50932/login_en.html');
await page.locator('#accountID').click();
await page.locator('#accountID').fill('root');
await page.locator('#passwordID2').click();
await page.locator('#passwordID').fill('gw1033356');
await page.locator('#passwordID').press('Enter');
await page.getByText('</body> </html>').contentFrame().locator('frame[name="left"]').contentFrame().getByText('Gateway settings').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="left"]').contentFrame().getByRole('link', { name: 'Port Settings' }).click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('#ID_goip_at_cmd').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('#ID_goip_at_cmd').fill('at+ccid');
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('checkbox', { name: 'All' }).check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('cell', { name: 'at+ccid   Send' }).getByRole('button').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('.listFoot > tbody > tr > td:nth-child(3) > input').check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_port_hwattr"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('button', { name: 'Refresh' }).click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('checkbox', { name: 'All' }).check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('.listFoot > tbody > tr > td:nth-child(3) > input').check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('.listFoot > tbody > tr > td:nth-child(3) > input').uncheck();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_port_hwattr"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('checkbox', { name: 'Enable' }).check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_basic_settings"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('cell', { name: 'Enable', exact: true }).click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('checkbox', { name: 'Enable' }).uncheck();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_basic_settings"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('#ID_goip_at_cmd').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('#ID_goip_at_cmd').fill('at+cgsn');
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('checkbox', { name: 'All' }).check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('cell', { name: 'at+cgsn   Send' }).getByRole('button').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('checkbox', { name: 'Enable' }).check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_basic_settings"]').click();

await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('#ID_goip_at_cmd').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('checkbox', { name: 'All' }).check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('#ID_goip_at_cmd').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('#ID_goip_at_cmd').fill('at+cgsn');
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('cell', { name: 'at+cgsn   Send' }).getByRole('button').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('.listFoot > tbody > tr > td:nth-child(3) > input').check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_port_hwattr"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('checkbox', { name: 'Enable' }).uncheck();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_basic_settings"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('.listFoot > tbody > tr > td:nth-child(3) > input').check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('.listFoot > tbody > tr > td:nth-child(3) > input').uncheck();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_port_hwattr"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('cell', { name: 'Enable', exact: true }).click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('cell', { name: 'Enable', exact: true }).check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('checkbox', { name: 'Enable' }).check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_basic_settings"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_port_hwattr"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('#ID_goip_at_cmd').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('#ID_goip_at_cmd').fill('at+cnum');
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('cell', { name: 'All', exact: true }).click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('cell', { name: 'at+cum   Send' }).getByRole('button').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('.listFoot > tbody > tr > td:nth-child(3)').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_port_hwattr"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('.listFoot > tbody > tr > td:nth-child(3)').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('.listFoot > tbody > tr > td:nth-child(3) > input').uncheck();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_port_hwattr"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('checkbox', { name: 'Enable' }).uncheck();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_basic_settings"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('cell', { name: 'Enable', exact: true }).click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('checkbox', { name: 'Enable' }).check();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().locator('input[name="btn_goip_basic_settings"]').click();
await page.getByText('</body> </html>').contentFrame().locator('frame[name="right"]').contentFrame().getByRole('checkbox', { name: 'Enable' }).uncheck();